### ISSUE TITLE
Select a starter template and push its code

### ISSUE THREAD

**Issue by Anupam-dagar** [Girls-Do-Code/Girls-Do-Code.github.io#1]
Delete the current repository code (except Readme.md) and push a starter template code.
A good resource is to check out materialize and bootstrap starter templates.

**Comment by Panda2498** [comment]
Can I resolve this issue?

**Comment by Anupam-dagar** [comment]
@Panda2498 yeah go ahead

**Comment by Panda2498** [comment]
I am done with this issue. Please check and tell if I need to add or delete any folders or docs.
