### ISSUE TITLE
make subsection and a cute css animation

### ISSUE THREAD

**Issue by gauthamzz** [Girls-Do-Code/Girls-Do-Code.github.io#12]
get animation from codepen or somewhere and add the animation in website.

eveyone can add one section.

**Comment by Tlazypanda** [comment]
I would be interested.Is there supposed to be animation for each section?

**Comment by gauthamzz** [comment]
you may do it.anyone can . we are trying to make a lot of animations come one after another.

**Comment by Panda2498** [comment]
May I resolve this issue?

**Comment by gauthamzz** [comment]
yeah eveyone can do this. Just append under the present one.
