### ISSUE TITLE
repository setup

### ISSUE THREAD

**Issue by Anupam-dagar** [Girls-Do-Code/Girls-Do-Code.github.io#17]
make a proper directory structure, delete files which are not required.
create a static folder which should have 3 subfolders namely "css", "js", "images" and move the respective files there.Also change the respective url in index.html for css,js and images.

**Comment by nikki1016** [comment]
can I fix it..

**Comment by ananya** [comment]
Can i do this

**Comment by Tlazypanda** [comment]
I would be interested.

**Comment by gauthamzz** [comment]
do it @nikki1016

**Comment by nikki1016** [comment]
should all css files be in same folder like bootstrap files that are currently in vendor/bootstrap folder?
Can I add favicon as well?
