### ISSUE TITLE
Add opensource women orgs info

### ISSUE THREAD

**Issue by gauthamzz** [Girls-Do-Code/Girls-Do-Code.github.io#20]
Add info about RGSOC ,pyladies etc.. make a section about how women can join opensource,
how they can get awards etc

Find out more info
and make a very good section as well

**Comment by ananya** [comment]
i want to do this

**Comment by KomalBhadani27** [comment]
I want to do this

**Comment by Tlazypanda** [comment]
I would be very much interested.If i can get a chance

**Comment by adiagg2000** [comment]
i want to do this

**Comment by Anupam-dagar** [comment]
@ananya-agrawal assigned

**Comment by gauthamzz** [comment]
Dagar it looks as if this repo needs more issues

**Comment by gauthamzz** [comment]
update on this issue @ananya-agrawal 
will assign to someone else,if no progress.

**Comment by aswinzz** [comment]
Anyone else can take up this issue

**Comment by Tlazypanda** [comment]
We can all take this up dividing into diff sections
1.WOMEN WHO CODE our title sponser
2.pyladies(python)
3.rgsoc(ruby)
4.os4w(opensource)
5.node girls

**Comment by ritikamotwani** [comment]
I would like to work on this issue.

**Comment by gauthamzz** [comment]
You can start working on it @ritikamotwanj
