### ISSUE TITLE
Refer your friends to contribute,star and fork this repo.

### ISSUE THREAD

**Issue by Tlazypanda** [Girls-Do-Code/Girls-Do-Code.github.io#22]
For all the positive female influences in your life,kindly ask them to join this repo to give them a headstart in the world of coding and more specifically a taste of opensource.

**Comment by gauthamzz** [comment]
I like this idea 🔥

**Comment by Tlazypanda** [comment]
Glad you liked it sir!

**Comment by gauthamzz** [comment]
Show any prof on comments and get points
