### ISSUE TITLE
fix the main page animation

### ISSUE THREAD

**Issue by Anupam-dagar** [Girls-Do-Code/Girls-Do-Code.github.io#23]
currently the animation take whole of page, any section added is coming over that animation which means the section is not scrolling.This is a major issue as it will hinder the progress of the website.
example can be seen here
https://esha23.github.io/Girls-who-code/

**Comment by Tlazypanda** [comment]
I would like to try just try.

**Comment by ananya** [comment]
@Anupam-dagar  a header like thing is also coming and not getting scroled

**Comment by ananya** [comment]
i will also work on it

**Comment by gauthamzz** [comment]
@tlazypanda assigned

**Comment by gauthamzz** [comment]
@ananya make issue
