### ISSUE TITLE
Adding smooth scroll for the navbar

### ISSUE THREAD

**Issue by Tlazypanda** [Girls-Do-Code/Girls-Do-Code.github.io#25]
Right now it jumps to the section abruptly.So js script reqd for the same.

**Comment by Tlazypanda** [comment]
Also Can i work on it?

**Comment by pradeepgangwar** [comment]
Finish other issues first. I am labeling it as unassigned.

**Comment by Esha23** [comment]
Can I try this?

**Comment by pradeepgangwar** [comment]
@Esha23 Assigned.
