### ISSUE TITLE
Correct footer alignment

### ISSUE THREAD

**Issue by PaiShoIroh** [Girls-Do-Code/Girls-Do-Code.github.io#27]
Footer is taking too much space. Correct it so that website can be opened in mobile phones and uniformity is maintained.

![image](https://user-images.githubusercontent.com/21156892/34907712-bdd11f80-f8a8-11e7-8e0b-9c7e0fe45b8e.png)

**Comment by Tlazypanda** [comment]
I would like to take this up.

**Comment by Tlazypanda** [comment]
But I think the problem might get resolved after my previous issue gets merged.

**Comment by gauthamzz** [comment]
duplicate  issue
yeah it will @Tlazypanda
