### ISSUE TITLE
fixing horizontal scroll bar

### ISSUE THREAD

**Issue by muskanchugh5** [Girls-Do-Code/Girls-Do-Code.github.io#30]
when the animation begins the horizontal scroll bar is not looking good at all .

**Comment by muskanchugh5** [comment]
can I resolve this

**Comment by aswinzz** [comment]
you are working on an issue right! @muskan6769

**Comment by muskanchugh5** [comment]
Yes, I am almost done with it..... I had to add a subsection

**Comment by Esha23** [comment]
I will do this..Can I??

**Comment by Tlazypanda** [comment]
i am interested

**Comment by gauthamzz** [comment]
ok @muskan6769 assigned.
Everyone finish your issues and ask for more. At max two issues per person,
