### ISSUE TITLE
Make the landing page smaller

### ISSUE THREAD

**Issue by aswinzz** [Girls-Do-Code/Girls-Do-Code.github.io#31]
As of now the code develop explore thing is coming in new lines.make it into a single line.

**Comment by muskanchugh5** [comment]
Can I do it

**Comment by ananya** [comment]
I will do this

**Comment by KomalBhadani27** [comment]
i wnat to do it

**Comment by Tlazypanda** [comment]
I would be interested

**Comment by Sangeetaaa** [comment]
i want to do this

**Comment by aswinzz** [comment]
@muskan6769  you can work on this

**Comment by muskanchugh5** [comment]
Sure ...  I'll do this
