### ISSUE TITLE
Make a section for contributors

### ISSUE THREAD

**Issue by aswinzz** [Girls-Do-Code/Girls-Do-Code.github.io#34]
make a grid and add all the girl contributors in it.

**Comment by muskanchugh5** [comment]
can I do it

**Comment by Sangeetaaa** [comment]
i will do it

**Comment by Esha23** [comment]
can I try?

**Comment by gauthamzz** [comment]
@muskan6769 i guess you have something assigned, @IIT2017032 assigened to you.
