### ISSUE TITLE
Add a new section called events 

### ISSUE THREAD

**Issue by gauthamzz** [Girls-Do-Code/Girls-Do-Code.github.io#37]
Make cards where deveolper events nearby will be displayed.
https://www.womenwhocode.com/events

**Comment by nikki1016** [comment]
can I do this?

**Comment by gauthamzz** [comment]
yeah okay @nikki1016

**Comment by nikki1016** [comment]
can u please help me ? since those events list  will change as per new events will add, so from where to get that events json or events data?

**Comment by gauthamzz** [comment]
add a json. create a sepearte page for it

**Comment by nikki1016** [comment]
can't have section of events like that in [opencode](https://opencode18.github.io/OpenCode-Collaborative/#projects)?

**Comment by gauthamzz** [comment]
Yeah thats also fine. But i dont think the designs of both the websites match.

**Comment by nikki1016** [comment]
both...girlswhocode and oepncode ?

**Comment by gauthamzz** [comment]
Im not clear what you mean, come on zuilp
