### ISSUE TITLE
create a logo for this repo

### ISSUE THREAD

**Issue by Anupam-dagar** [Girls-Do-Code/Girls-Do-Code.github.io#4]

**Comment by ananya** [comment]
i want to do this

**Comment by Tlazypanda** [comment]
I would be interested.

**Comment by aswinzz** [comment]
@ananya-agrawal you can do it

**Comment by Tlazypanda** [comment]
![girls who 1](https://user-images.githubusercontent.com/33183263/34877241-46615fa6-f7cb-11e7-851d-51de54614ed1.png)

Hey sir! Check this out.
