### ISSUE TITLE
The Contact section in the nav  bar doesn't work

### ISSUE THREAD

**Issue by ritikamotwani** [Girls-Do-Code/Girls-Do-Code.github.io#41]
The contact section should have the contact info of the organizers.
I would like to work on it.

**Comment by gauthamzz** [comment]
But there is no organisers for this 😅
You can put like girls who want to be organisers of girls who code . Anyone wants to be an organiser of girls who code . Comment . Will add as organiser .

**Comment by gauthamzz** [comment]
Only for girls and you can work on it @rithikamotwani 20 points issue
