### ISSUE TITLE
Add a video section with a video that promotes our sponser Women Who code

### ISSUE THREAD

**Issue by Tlazypanda** [Girls-Do-Code/Girls-Do-Code.github.io#51]
Check this link out
https://www.youtube.com/watch?v=k1Pu0_tIgR4

**Comment by Tlazypanda** [comment]
Can I work on it?

**Comment by gauthamzz** [comment]
Nah not a good idea

**Comment by gauthamzz** [comment]
If you can make a video about girls who code, properly edited etc. with a team of max 3 people will give 50 points to each for that
