### ISSUE TITLE
Fix values section

### ISSUE THREAD

**Issue by gauthamzz** [Girls-Do-Code/Girls-Do-Code.github.io#53]
Doesn't look good.

And the values mentioned are not certain. Define better values.

Anyone can suggest values.

**Comment by ritikamotwani** [comment]
I want to work on it.

**Comment by gauthamzz** [comment]
yeah sure @ritikamotwani 
Suggest values though

**Comment by ritikamotwani** [comment]
Just a question which one is the values section :stuck_out_tongue:

**Comment by gauthamzz** [comment]
https://opencode18.github.io/Girls-who-code/#goals
