### ISSUE TITLE
Add a quote related to women in opensource as heading

### ISSUE THREAD

**Issue by aswinzz** [Girls-Do-Code/Girls-Do-Code.github.io#6]

**Comment by ananya** [comment]
i want to do this

**Comment by ananya** [comment]
where it is needed to be added

**Comment by aswinzz** [comment]
@ananya-agrawal complete the issue assigned to you then only we can assign you

**Comment by Tlazypanda** [comment]
Sir, can i take up the issue?

**Comment by muskanchugh5** [comment]
sir can i do it

**Comment by adiagg2000** [comment]
can i do this

**Comment by KomalBhadani27** [comment]
I would like to do this.

**Comment by Anupam-dagar** [comment]
Don't call anyone sir on GitHub :smile: 
@Tlazypanda assigned

**Comment by pradeepgangwar** [comment]
@Tlazypanda is working on #12 and #23 so let's assign @muskan6769 to this.
assigned to @muskan6769

**Comment by gauthamzz** [comment]
Two issue maximum per person , finish old ones
