### ISSUE TITLE
make landing section, goals and "only 1 in 10 ...." section fullscreen

### ISSUE THREAD

**Issue by Anupam-dagar** [Girls-Do-Code/Girls-Do-Code.github.io#60]
basically, the section must cover whole screen.
P.S take care of responsiveness while doing this

**Comment by nikki1016** [comment]
i have done that part along with adding events section

**Comment by Anupam-dagar** [comment]
your live in PR does not have the changes which are required in this issue, i checked just now

**Comment by nikki1016** [comment]
but not commited yet that one 
![is](https://user-images.githubusercontent.com/26041681/35164628-2263163e-fd71-11e7-9607-d100a41ae6be.png)
is it ok or need to do something else ?

**Comment by Anupam-dagar** [comment]
you can have this assigned to you and then push
