### ISSUE TITLE
Add a logo for Girls-who-code in Navbar

### ISSUE THREAD

**Issue by abhinavk96** [Girls-Do-Code/Girls-Do-Code.github.io#61]
The logo will serve as the generic logo for Girls-who-code website. It should not disrupt the responsivity.

**Comment by muskanchugh5** [comment]
i will do this

**Comment by gauthamzz** [comment]
You need to make logo as well

**Comment by muskanchugh5** [comment]
can't I get it from net??

**Comment by gauthamzz** [comment]
You should slightly modify it, you can search for it and comment on this thread or tell in Zulip . After logo is approved you can finish

**Comment by muskan6769** [comment]
what type of logo ..I need to put?

**Comment by muskanchugh5** [comment]
okk
