### ISSUE TITLE
Update the contributors section

### ISSUE THREAD

**Issue by ritikamotwani** [Girls-Do-Code/Girls-Do-Code.github.io#68]
There are some problems in the contributors section
1. It does not appear in the nav-bar
2. It looks abrupt.
![image](https://user-images.githubusercontent.com/22127980/35229977-d1b7dd5e-ffba-11e7-90e4-a20748a0b642.png)
I would like to work on this and solve the issue.

**Comment by gauthamzz** [comment]
yes, make it responsive as well. Try to not use the image and use the changing gradient like the div's on top of it. @ritikamotwani assigned.

**Comment by ritikamotwani** [comment]
Okay!
